# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: niklasnilsson
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: shui
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shui-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::376129862797:role/LambdaDynamoApis3fullaccessRole
  

functions:
  PostMsg:
    handler: functions/PostMsg/index.handler
    events:
      - httpApi:
          path: /post
          method: post
  GetAllMsg:
    handler: functions/GetAllMsg/index.handler
    events:
      - httpApi:
          path: /posts
          method: get
  DeleteMsg:
    handler: functions/DeleteMsg/index.handler
    events:
      - httpApi:
          path: /post/{id}
          method: delete
  UpdateMsg:
    handler: functions/UpdateMsg/index.handler
    events:
      - httpApi:
          path: /post/change/{id}
          method: put
          
resources:
  Resources:
    ShuiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'shui-backendDB'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST